import Head from "next/head";
import { useState } from "react";
import { TokenAddresses } from "../assets/data/data";
import TokenRow from "@components/TokenRow";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div id="home-container" className="p-10">

                <div className="text-xl mb-5">Thess are most popular tokens in sushiswap.</div>
                <div id="table-part" className="border-2 border-slate-400">
                    <div className="flex items-center bg-slate-300 h-16 p-4">
                        <div className="w-1/12 font-bold text-xl">Index</div>
                        <div className="w-1/6 font-bold text-xl">Name</div>
                        <div className="w-1/12 font-bold text-xl">Decimals</div>
                        <div className="w-1/6 font-bold text-xl">Symbol</div>
                        <div className="w-5/12 font-bold text-xl">Address</div>
                    </div>
                    {
                        TokenAddresses.map((tokenAddress, index) => (
                            <TokenRow tokenAddress={tokenAddress} index={index} />
                        ))
                    }
                </div>

            </div>
        </div >
    )
}
